fix: use ref_name to point to branch

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -3,7 +3,7 @@ run-name: >-
   Build OpenWrt
   ${{ (github.event_name == 'workflow_dispatch' && 'manually') || (github.event_name == 'schedule' && 'on schedule') || (github.event_name == 'push' && 'on update') || 'unexpectedly' }}
   for reference
-  ${{ (github.event_name == 'workflow_dispatch' && inputs.repository_ref != '') && inputs.repository_ref || github.ref }}
+  ${{ (github.event_name == 'workflow_dispatch' && inputs.repository_ref != '') && inputs.repository_ref || github.ref_name }}
   
 
 on:
@@ -106,7 +106,7 @@ jobs:
         uses: actions/checkout@v4
         with:
           path: "custom_repo"
-          ref: ${{ (github.event_name == 'workflow_dispatch' && inputs.repository_ref != '') && inputs.repository_ref || github.ref }}
+          ref: ${{ (github.event_name == 'workflow_dispatch' && inputs.repository_ref != '') && inputs.repository_ref || github.ref_name }}
 
       - name: Add extra package feeds
         run: |
@@ -166,12 +166,12 @@ jobs:
                 exit 1
               fi
 
-              # If the URL does not contain "://", treat it as a GitHub reference
+              # If the URL does not contain "://", treat it as a github.ref_nameerence
               if [[ "$url" != *"://"* ]]; then
                   IFS='/' read -r -a parts <<< "$url"
 
                   if [[ ${#parts[@]} -ne 3 ]]; then
-                    echo "Invalid GitHub reference format: $url" >&2
+                    echo "Invalid github.ref_nameerence format: $url" >&2
                     echo "::endgroup::"
                     exit 1
                   fi
@@ -213,7 +213,7 @@ jobs:
   release:
     name: Create release
     needs: [check_commits, build]
-    if: ${{ (needs.build.result == 'success') && (((github.event_name == 'workflow_dispatch' && inputs.repository_ref != '') && inputs.repository_ref || github.ref) == 'main') }}
+    if: ${{ (needs.build.result == 'success') && (((github.event_name == 'workflow_dispatch' && inputs.repository_ref != '') && inputs.repository_ref || github.ref_name) == 'main') }}
     runs-on: ubuntu-latest
     steps:
       - name: Download artifacts
