refactor: patch dark mode on argon theme to support luci-mod-dashboard

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -200,6 +200,22 @@ jobs:
           rm -rf luci-theme-argon; git clone "${GITHUB_SERVER_URL}/jerrykuku/luci-theme-argon.git" luci-theme-argon
           rm -rf luci-app-argon-config; git clone "${GITHUB_SERVER_URL}/jerrykuku/luci-app-argon-config.git" luci-app-argon-config
           echo "::endgroup::"
+          echo "::group::Patching argon dark theme for luci-mod-dashboard"
+          cd luci-argon-theme
+          git remote add alryaz "${GITHUB_SERVER_URL}/alryaz/luci-theme-argon.git"
+          git fetch alryaz patch-1
+          git stash push --include-untracked --message "backup-before-alryaz-merge"
+          if git merge --no-commit --no-ff alryaz/patch-1; then
+            git commit -m "Merged alryaz/patch-1"
+            git stash drop stash@{0} || true
+          else
+            echo "::warning::Could not fix Argon theme's luci-mod-dashboard dark mode. Skipping..."
+            git merge --abort || true
+            git reset --hard
+            git clean -fd
+            git stash pop || true
+          fi
+          echo "::endgroup::"
 
       - name: Add custom patches
         run: |
